karma.conf.js
src/plugin/geopackage/geopackage.js
src/plugin/geopackage/geopackageexporter.js
src/plugin/geopackage/geopackageimportui.js
src/plugin/geopackage/geopackageplugin.js
src/plugin/geopackage/geopackageprovider.js
src/plugin/geopackage/geopackagerequesthandler.js
src/plugin/geopackage/geopackagetile.js
src/plugin/geopackage/geopackagetilelayerconfig.js
src/plugin/geopackage/geopackagevectorlayerconfig.js
src/plugin/geopackage/mime.js
test/plugin/geopackage/geopackageplugin.test.js
test/plugin/geopackage/geopackageprovider.test.js

Refactored everything in `src/plugin` to use `goog.module` and removed all `declareLegacyNamespace` calls. I did a pass over the code to add explicit requires, convert `var` to `const/let`, and some other minor cleanup.
I came across a bug where Geopackage providers would not be restored properly from settings if you had multiple loaded. `GeoPackageProvider` had a `getInstance` call from `goog.addSingletonGetter`, which causes the data manager to create the provider using that method. When subsequent providers are created, they reuse the first instance and make changes to it. It didn't seem like the provider should have a singleton, so I removed `getInstance` from it.
Demo: https://brash-lock.surge.sh/
Example GPKG files can be found here:
- https://www.geopackage.org/data.html
- …

refactor(goog): transform source to use goog.module

---

package.json

This will add a pinned `nan@2.14.0` dependency to the generated `opensphere-electron/app/package.json`, which fixes an issue building the native `canvas` dependency on Windows.

fix(electron): fix native build of canvas by electron-builder

---

README.md

`yarn install` will fail unless you install canvas on your machine when developing with electron. This should fix the problem

chore(readme): Update README for Electron development

---

src/plugin/geopackage/geopackage.js

`goog.log.getLogger` returns a `goog.log.Logger`, not `goog.debug.Logger`. This will be reported as an error if the Closure library is updated.

fix(goog): fix logger typing

---

src/plugin/geopackage/geopackageprovider.js

Uses a new checkbox directive to support turning the full file on, showing a warning in cases with a lot of layers.

feat(provider): updates provider to support turning on full gpkg file

---

externs/geopackage.js
index.js
karma.conf.js
package.json
src/plugin/geopackage/geopackageprovider.js
src/plugin/geopackage/geopackagetilelayerconfig.js
src/worker/gpkg.worker.js
test/plugin/geopackage/geopackageprovider.test.js

**Note:** This PR was moved from https://github.com/wallw-bits/opensphere-plugin-geopackage/pull/2 and updated to the latest changes on `master`.
Use the reprojection support in geopackage-js to allow the OpenSphere side to use a more typical XYZ grid with an extent and have geopackage-js stitch and resample the new tiles together. This allows better support from Cesium (especially for different origins per tile matrix), in addition to showing the raster layer in more resolutions than what may be defined in the GeoPackage (resulting in a better user experience).
Note: "reprojection" is an odd word here. By default, OpenSphere will still enforce the reprojection flag in config. In this case, GeoPackages in the application projection will simply be restitched/resampled into other tiles, but …

feat(gpkg): Tile layers now use reprojection/stitching

---

package.json

`better-sqlite3@7.1.4` was built on Ubuntu 20.04, which uses glibc 2.29. The prebuild script for the package requires that version of glibc, which is not available on lesser versions of Ubuntu, RHEL 7, etc. This will be resolved once JoshuaWise/better-sqlite3/pull/631 is merged/released, but for now the workaround is to roll back to 7.1.2.

fix(sqlite): downgrade better-sqlite3 to 7.1.2 to fix glibc incompatibility

---

src/worker/gpkg.worker.js

Paths were not being resolved/created correctly in the Windows Electron build. To resolve this, the worker now uses `path.dirname` and `path.sep` when running in a Node environment.

Fix Windows path resolution and explicitly include better-sqlite3 in Electron

---

src/plugin/geopackage/geopackageexporter.js

- `os.osDataManager` has been replaced by `os.dataManager` in ngageoint/opensphere/pull/1314. The reference has been replaced with a direct dependency to the DataManager.
- Updated other global references in the exporter.

refactor(export): update data manager and global references

---

src/plugin/geopackage/geopackageexporter.js
src/plugin/geopackage/geopackageprovider.js
src/plugin/geopackage/geopackagetilelayerconfig.js
src/plugin/geopackage/geopackagevectorlayerconfig.js
src/plugin/geopackage/mime.js

This replaces some remaining JSDoc global references, and triggers a release with the latest module refactor.

feat: replace global refs and trigger release

---

package.json
src/plugin/geopackage/geopackageprovider.js
src/plugin/geopackage/geopackagetilelayerconfig.js
src/worker/gpkg.worker.js

Upgrades the geopackage dependency to beta.33 to fix a bug with multiple tile tables in a single gpkg file. Also works around an issue in 2D mode where requesting tiles outside of the default world extent would either result in distorted tiles or flat out crashing the browser in some cases.

fix(tiles): use tile scaling to support gpkg tiles at all zooms

---

src/worker/gpkg.worker.js

If a GPKG has a `gpkg_data_columns` table, the columns returned by `getInfoForTable` may have differing `name` and `displayName` fields. We were using the `name` field, but GeoJSON returned by `iterateGeoJSONFeatures` uses the `displayName` field for feature properties. This was breaking things like feature info, labels, etc that map source columns to feature properties.

fix(columns): create source columns with the same name used by features

---

package.json

`better-sqlite3@7.4.1` includes prebuilt binaries for Electron 13, which allows the build to simply download them instead of building them locally. The updated release of `@ngageoint/geopackage` also uses this version.

feat(deps): upgrade better-sqlite to support electron 13 prebuilt binaries

---

src/plugin/geopackage/geopackagetilelayerconfig.js

`BaseProvider` is now a module, and the default export for a module cannot be destructured in the import assignment.

fix(tile): don't destructure default exports

---

src/plugin/geopackage/geopackageimportui.js
src/plugin/geopackage/geopackageplugin.js
src/plugin/geopackage/geopackageprovider.js
test/plugin/geopackage/geopackage.mock.js
test/plugin/geopackage/geopackageplugin.test.js

- Updated the local file url enabled API that changed in ngageoint/opensphere/pull/1335. Tests will fail on this until that PR is merged.
- OpenSphere dependency changes introduced a new vendor library requirement (`markdownit`, used by the TUI editor via feature edit) if `os.MapContainer` was required. This was being introduced to GPKG tests by `os.mock.js`, which does way more than these tests need. I made a local mock that only initializes settings and net handlers.
- Replaced `os.dataManager` with `DataManager.getInstance()`, which will be the preferred approach moving forward.

refactor(file): use getter to check if local file urls are enabled

---

src/plugin/geopackage/geopackageexporter.js
src/plugin/geopackage/geopackagevectorlayerconfig.js

The geometry column seems to be treated special by Geopackages and contains blob data that doesn't display nicely. This filters it out of the source columns in the same way we do with geometry columns in other feature layers.

fix(columns): filters out empty geometry column

---

src/plugin/geopackage/geopackagetilelayerconfig.js
src/worker/gpkg.worker.js

Reenables world wrapping in the layer config for geopackage tile layers and fixes them loading by normalizing the coordinates that we send to the library to request the tiles.

fix(tiles): enables and fixes tile world wrapping

---

src/plugin/geopackage/geopackageimportui.js

Resolves compiler errors introduced in ngageoint/opensphere/pull/1346, due to the compiler not knowing specific enough types.

fix(import): provide appropriate types to the compiler

---

src/plugin/geopackage/geopackageimportui.js

Uses a direct reference to the settings module, as `os.settings` will be removed in the future.

refactor(settings): replace os.settings with module ref

---

src/plugin/geopackage/geopackage.js
src/plugin/geopackage/geopackageexporter.js
src/plugin/geopackage/geopackageimportui.js
src/plugin/geopackage/geopackageplugin.js
src/plugin/geopackage/geopackageprovider.js
src/plugin/geopackage/geopackagerequesthandler.js
src/plugin/geopackage/geopackagetile.js
src/plugin/geopackage/geopackagetilelayerconfig.js
src/plugin/geopackage/geopackagevectorlayerconfig.js
src/plugin/geopackage/mime.js
test/plugin/geopackage/geopackageplugin.test.js
test/plugin/geopackage/geopackageprovider.test.js

Converts all files from `goog.module` to ES modules.
Following the [Google JS style guide](https://google.github.io/styleguide/jsguide.html#es-module-exports), this also converts all default exports to named exports. The main drive behind this is to help enforce consistent import naming between modules.

refactor(es): transform to es modules and convert default exports

---

package.json
src/plugin/geopackage/geopackageprovider.js

- Relative parent imports (using `../`) have been replaced with module-relative imports.
- Import statements have been sorted by group (external -> internal -> relative sibling) and alphabetically by path within each group.

refactor(import): replace parent relative imports and sort

---

src/plugin/geopackage/geopackagevectorlayerconfig.js

Converted requires to imports for modules updated in ngageoint/opensphere/pull/1363. This was fully scripted.
The build for this will fail until the OpenSphere PR is merged.

refactor(es): convert requires to imports

---

package.json

Updates the Closure webpack plugin and resolver to use the latest Closure compiler. This is paired with a similar update in OpenSphere, in ngageoint/opensphere/pull/1369.

build(gcc): use latest closure compiler
